version: "3.9"
    
services:
#Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: learnphp
    networks:
      - learnphp
  #phpMyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: .env
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $DB_DATABASE
    networks:
      - learnphp
networks:
  learnphp:
volumes:
  db_data: