version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ".:/www"
            - .docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - dev-network

    php:
        image: hellossx/php-fpm
        volumes:
            - ".:/www"
        networks:
            - dev-network

    db:
        image: mysql:5.7
        environment:
         - MYSQL_ROOT_PASSWORD: password
         - MYSQL_DATABASE: root
         - MYSQL_USER: root
         - MYSQL_PASSWORD: root

        ports:
          - "3306:3306"
        volumes:
         - .docker/volumes/mysql:/var/lib/mysql
        networks:
            - dev-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
          - 8081:80
        environment:
          - PMA_ARBITRARY= 1
          - MYSQL_ROOT_PASSWORD= password
        networks:
            - dev-network

    beanstalkd:
        image: hellossx/beanstalkd
        expose:
         - "11300"
        networks:
            - dev-network

    beanstalkd_console:
        image: agaveapi/beanstalkd-console
        environment:
         - BEANSTALKD_HOST=beanstalkd
         - BEANSTALKD_PORT=11300
        expose:
         - "80"
        ports:
         - "8082:80"
        networks:
            - dev-network

    mailhog:
      image: mailhog/mailhog
      ports:
        - "8083:8025"
      networks:
          - dev-network

    redis:
        image: tutum/redis
        expose:
         - "6379"
        environment:
         - REDIS_PASS=**None**
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge